tap "homebrew/cask-fonts"
tap "nikitabobko/tap"

brew "fzf"
brew "htop"
brew "jq"
brew "neovim"
brew "nvm"
brew "powerlevel10k"
brew "spicetify-cli"
brew "stow"
brew "uv"
brew "zoxide"

cask "nikitabobko/tap/aerospace"
cask "font-hack-nerd-font"
cask "iterm2"
cask "raycast"
