#!/usr/bin/env sh
set -eu

omz_dir="${ZSH:-$HOME/.oh-my-zsh}"
custom_dir="${ZSH_CUSTOM:-$omz_dir/custom}"

if [ ! -f "$omz_dir/oh-my-zsh.sh" ]; then
  if [ -e "$omz_dir" ]; then
    echo "$omz_dir exists but does not look like an Oh My Zsh install." >&2
    exit 1
  fi

  RUNZSH=no CHSH=no KEEP_ZSHRC=yes \
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

mkdir -p "$custom_dir/plugins"

install_plugin() {
  name=$1
  url=$2
  dest="$custom_dir/plugins/$name"

  if [ -d "$dest/.git" ]; then
    echo "$name already installed at $dest"
    return
  fi

  if [ -e "$dest" ]; then
    echo "$dest exists but is not a Git checkout." >&2
    exit 1
  fi

  git clone --depth=1 "$url" "$dest"
}

install_plugin zsh-autosuggestions https://github.com/zsh-users/zsh-autosuggestions.git
install_plugin zsh-defer https://github.com/romkatv/zsh-defer.git
install_plugin zsh-syntax-highlighting https://github.com/zsh-users/zsh-syntax-highlighting.git
